### ISSUE TITLE
Support for .png format is broken

### ISSUE THREAD

**Issue by mrquincle** [potherca/GraphvizWebEditor#16]
Beautifully done!

http://graphviz.herokuapp.com/?token=f2d35ba02a9b3bd474056e808a4eb27c

The default setting is broken however:

    Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pic plain plain-ext pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4

Perhaps it is better to switch the default to `svg`?

**Comment by potherca** [comment]
Fixed by switching to the new Heroku Cedar 14 stack and changing to a different buildpack for Graphviz (see commit f946a91)
